### ISSUE TITLE
urllib3 error

### ISSUE THREAD

**Issue by spinning-fantasies** [spinning-fantasies/mastodon-bot-tutorial#3]
```
python3 mastodon_bot/main.py
/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='3615.computer', port=443): Max retries exceeded with url: /api/v1/apps (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/mastodon/authentication.py", line 73, in create_app
    response = requests.post(f"{api_base_url}/api/v1/apps", data=request_data, headers=headers, timeout=request_timeout)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='3615.computer', port=443): Max retries exceeded with url: /api/v1/apps (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/mastodon_bot/main.py", line 26, in <module>
    main()
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/mastodon_bot/main.py", line 22, in main
    register_app()
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/mastodon_bot/main.py", line 10, in register_app
    Mastodon.create_app(
  File "/Users/mathieu/Code/Python/mastodon-bot-tutorial/lib/python3.9/site-packages/mastodon/authentication.py", line 76, in create_app
    raise MastodonNetworkError(f"Could not complete request: {e}")
mastodon.errors.MastodonNetworkError: Could not complete request: HTTPSConnectionPool(host='3615.computer', port=443): Max retries exceeded with url: /api/v1/apps (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALE
```

**Comment by sanders41** [comment]
Can you check your `Applications/Python 3.9` directory and see if it has `Install Certificates.command` in it? If it does try double clicking that to install and see if it resolves the error.

**Comment by spinning-fantasies** [comment]
Well I'm afraid I don't even have an ``Applications/Python 3.9`` directory 😕 

I do have a ``~/Library/Python/3.9`` directory but I didn't find any ``Install Certificates.command`` in it

**Comment by sanders41** [comment]
Ok, let's see if running this works: `pip install --upgrade certifi`
